### ISSUE TITLE
Add some new git commands which is not already present.

### ISSUE THREAD

**Issue by jay1310** [jay1310/git_commands_collection#14]
Can you add some more commands to the gitcmds.txt file which can help the users?

**Comment by Princy06** [comment]
can i work on this issue? please assign me this.

**Comment by jay1310** [comment]
@Princy06 
Yeah, go for it.

**Comment by niharikabharti** [comment]
Can I work on this issue?Please assign me

**Comment by jay1310** [comment]
Yes @niharikabharti , you can send the PR with some some new commands.

**Comment by Supriyabce** [comment]
I want to work on this

**Comment by Supriyabce** [comment]
can i work on this issue? please assign me this.

**Comment by jay1310** [comment]
@Supriyabce Go for it 👍👍
